services:
  api:
    image: "ghcr.io/rin-yato/api:prod"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.rinyato.com`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.docker.network=proxy"
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 2
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
